Payroll.Web/Areas/Admin/Controllers/RoleAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Payroll.Domain;
using Payroll.Domain.Entities;
using Payroll.Domain.Repositories;
using Payroll.Web.Identity;


namespace Payroll.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleAdminController : Controller
    {
        private RoleStore _roleStore;
       public  RoleAdminController(RoleStore roleStore)
        {
            _roleStore = roleStore;
        }
        // GET: Admin/RoleAdmin
        public ActionResult Index()
        {


            var roles = _roleStore.Roles;


            return View(roles);
        }

        public ActionResult Create()
        {
            return View();

        }
        [HttpPost]
        [ActionName("Create")]
        [ValidateAntiForgeryToken]
        public ActionResult Save(IdentityRole role)
        {
            if (ModelState.IsValid)
            {
                _roleStore.CreateAsync(role).Wait();
                return RedirectToAction("Index");
            }

            return View();
        }

        
        [HttpPost]
        public async Task<ActionResult> Delete(IdentityRole role)
        {
           
            _roleStore.DeleteAsync(role).Wait();

            return RedirectToAction("Index");
        }


    }
}

Payroll.Web/Areas/Admin/Controllers/UserAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Payroll.Web.Areas.Admin.Models;
using Payroll.Web.Identity;

namespace Payroll.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserAdminController : Controller
    {
        private readonly UserManager<IdentityUser, Guid> _userManager;
        private readonly RoleStore _roleStore;

        public UserAdminController(UserManager<IdentityUser, Guid> userManager,RoleStore roleStore)
        {
            _userManager= userManager;
            _roleStore = roleStore;


        }
        // GET: Admin/UserAdmin
        public ActionResult Index()
        {


            var users = _userManager.Users.ToList();
            
            UserViewModel vm= new UserViewModel(_userManager);
            
            List<UserViewModel> list = vm.ConvertIdentityUserToUserViewModel(users);

            return View(list);
        }

        public ActionResult Create()
        {
            
           ViewBag.Roles = new SelectList(_roleStore.Roles, "Id", "Name");
            return View();
        }


        [HttpPost]
        [ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Save(UserViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                //check if the we have user with same employee code
                if (_userManager.Users.Count(r => r.EmployeeCode==userViewModel.EmployeeCode)>0)
                {
                    AddErrors(new IdentityResult("EmployeeCode already taken."));
                }
                else
                {
                    var newIdentityUser = new IdentityUser(userViewModel.UserName, userViewModel.EmployeeCode);
                    IdentityResult result =await _userManager.CreateAsync(newIdentityUser,userViewModel.Password);
                    if (result.Succeeded)
                    {
                        IdentityRole role = await _roleStore.FindByIdAsync(new Guid(userViewModel.RoleId));
                        result = await _userManager.AddToRoleAsync(newIdentityUser.Id, role.Name);
                        if (result.Succeeded)
                        {
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            AddErrors(result);
                        }
                    }
                    else
                    {
                        AddErrors(result);
                    }

                }

            }
            ViewBag.Roles = new SelectList(_roleStore.Roles, "Id", "Name",userViewModel.RoleId);
            return View(userViewModel);
        }



        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        public ActionResult Delete(UserViewModel userViewModel)
        {

            IdentityUser user = _userManager.FindById(userViewModel.Id);
          IdentityResult result= _userManager.Delete(user);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }

            return View("Error", model:"User cannot be deleted!!!");

        }
    }
}

Payroll.Web/Areas/Admin/Views/Shared/_DetailsDialog.cshtml
<div class="modal fade" id="payrollDetailPopupDialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
       <div class="modal-dialog modal-sm" role="document">
           <div class="modal-content">
               <div class="modal-header">
                   <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                   <h4 class="modal-title" id="dialogTitle">Details...</h4>
               </div>
               <div class="modal-body" id="payrollDetailPopupDialogContent">
                   
               </div>
               <div class="modal-footer">
                   <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
               </div>
           </div>
       </div>
   </div>

Payroll.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_DetailsDialog")
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Payroll Application", "Index", "Home", new {area = "Admin"}, new {@class = "navbar-brand"})
            @Html.ActionLink("Roles", "Index", "RoleAdmin", new {area = "Admin"}, new {@class = "navbar-brand"})
            @Html.ActionLink("Users", "Index", "UserAdmin", new {area = "Admin"}, new {@class = "navbar-brand"})
            @Html.ActionLink("Employees", "Index", "Employee", new {area = "Admin"}, new {@class = "navbar-brand"})
            @Html.ActionLink("Department", "Index", "Department", new {area = "Admin"}, new {@class = "navbar-brand"})
          
        </div>
        <div class="navbar-collapse collapse">
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/jqueryajax")

<script>
    function showDetailDialog() {
        $('#payrollDetailPopupDialog').modal('show');
    }
    

</script>
@RenderSection("scripts", required: false)
</body>
</html>